### PR TITLE
Ident c195 connect with google

### PR DESCRIPTION
**Pull request by TylorS**
Manditory Checks
---

- [x] I added new tests for the issue I fixed or the feature I built
- [x] I ran `npm test` for the package I'm modifying
- [x] I used `npm run commit` instead of `git commit`

---

- Switches from awesome-typescript-loader to ts-loader to resolve a large number of obscure build errors. This could be the source of some of Bruno's pain recently. 
- Completes UAT1 with connecting to google

A passing UAT1 requires environment variables `GOOGLE_TEST_EMAIL` and `GOOGLE_TEST_EMAIL_PASSWORD` to be present and valid. PM me on slack if you need the credentials for the test email and password.

### CODE REVIEW

**Comment by TylorS** [comment]
[IDENT/UAT1: Connect with Google (creating account)](https://trello.com/c/onl5zAsR/195-ident-uat1-connect-with-google-creating-account)

**Review by sdebaun — CHANGES_REQUESTED** [review]
Need to document the environment variables needed. Add a section to the README?

e2e test doesnt cover landing back on a dashboard with email as described in UAT

**Comment by TylorS** [comment]
@sdebaun documentation has been added to the README and the E2E test has been updated to check the dummy dashboard page for the user email.

**Review by sdebaun — APPROVED** [review]

**Comment by sdebaun** [comment]
[IDENT/UAT1: Connect with Google (creating account)](https://trello.com/c/onl5zAsR/195-ident-uat1-connect-with-google-creating-account)

**Pull request merged**
